/* Generated By:JavaCC: Do not edit this line. NosqlConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface NosqlConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INSERT = 4;
  /** RegularExpression Id. */
  int DB = 5;
  /** RegularExpression Id. */
  int NAME = 6;
  /** RegularExpression Id. */
  int KEY_VALUE = 7;
  /** RegularExpression Id. */
  int QUO = 8;
  /** RegularExpression Id. */
  int COMMA = 9;
  /** RegularExpression Id. */
  int BRACE_OPEN = 10;
  /** RegularExpression Id. */
  int BRACE_CLOSE = 11;
  /** RegularExpression Id. */
  int COLON = 12;
  /** RegularExpression Id. */
  int OPEN_PAR = 13;
  /** RegularExpression Id. */
  int CLOSE_PAR = 14;
  /** RegularExpression Id. */
  int DOT = 15;
  /** RegularExpression Id. */
  int EOL = 16;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"insert\"",
    "\"db\"",
    "<NAME>",
    "<KEY_VALUE>",
    "\"\\\"\"",
    "\",\"",
    "\"{\"",
    "\"}\"",
    "\":\"",
    "\"(\"",
    "\")\"",
    "\".\"",
    "\"\\n\"",
  };

}
